version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: poc_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres  # base principal, pero crearemos otras dos manualmente (raw y stage)
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
