[package]
name = "rayon-etl"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10"
csv = "1.3"
rusqlite = "0.30.0"
dashmap = "5.5"
sysinfo = "0.30.4"
serde = { version = "1.0", features = ["derive"] }