[package]
name = "polars-etl"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.37.0", features = [
    "lazy",
    "csv",
    "strings",
    "regex",
    "sql",
    "dtype-decimal",
    "streaming"
] }
rusqlite = "0.30"
sysinfo = "0.30.13"